### ISSUE TITLE
Sync own listings between GC and OC

### ISSUE THREAD

**Issue by Lineflyer** [FriedrichFroebel/cmanager#33]
Please forgive me if this is already supported but I am unaware about usage:

AFAIR the old cmanager had the possibility to sync own listings between both platforms.
I could however not find out how to use it or whether this is really (still) included.

As I consider double listings (GC+OC) meaningful to support OC also with caches I already listed on GC only at the moment, but can't afford manual sync initially and on each change, such feature would be really helpful.

I cannot support with implementation but would be willing to test such implementation.

**Comment by FriedrichFroebel** [comment]
No, this application never supported it - you are probably mixing this up with [ocprop](https://wiki.opencaching.de/index.php/Ocprop). At the moment I do not have any plans on implementing this (rather large) feature as well, but if someone decides to implement it, why not.

**Comment by Lineflyer** [comment]
You are right:
I mixed it up with ocprop.
So its more a feature request
