### ISSUE TITLE
Msg: The shadow list retrieval has been disabled temporarily as the API endpoint seems to be broken for now.

### ISSUE THREAD

**Issue by roseswe** [FriedrichFroebel/cmanager#37]
JFYI, not sure if this is an issue at all. Thanks a lot for maintaining this program!

----
```
$ java -jar cm-0.5.1.jar 
The shadow list retrieval has been disabled temporarily as the API endpoint seems to be broken for now.
The shadow list retrieval has been disabled temporarily as the API endpoint seems to be broken for now.


```

**Comment by FriedrichFroebel** [comment]
This actually is a message introduced by me when the shadow list API stopped working, see the discussion in the German OC forum: https://forum.opencaching.de/index.php?topic=4348.msg64722#msg64722. The progress of transitioning the shadow list to another implementation is being tracked in #5. (In fact most regular terminal outputs should be basic information messages, while Java exceptions in the terminal output probably indicate that something is not working within the application.)
