### ISSUE TITLE
Compare Event date (=hidden date) when syncing Event-Caches

### ISSUE THREAD

**Issue by jsteltze** [FriedrichFroebel/cmanager#38]
In some cases the synchronization of event caches is not successful, especially if there is a series of events which always takes place at the same location.
Therefore I would suggest: in case of Event-Caches the event date (=hidden date of the cache) should be compared to prevent mis-matches.

**Comment by FriedrichFroebel** [comment]
Duplicate of #17. The latest master branch should support it already, although this has not yet been released officially.
